### ISSUE TITLE
Images for README.md

### ISSUE THREAD

**Issue by marcopovitch** [marcopovitch/sl2influxdb#1]
![latency_trace](https://cloud.githubusercontent.com/assets/4367036/12712706/95c4a38c-c8ca-11e5-8fa7-9c40bbdb8d24.png)
![trace](https://cloud.githubusercontent.com/assets/4367036/12712707/95e9f498-c8ca-11e5-8115-cabb66dbf692.png)

**Comment by marcopovitch** [comment]
<img width="1379" alt="map" src="https://cloud.githubusercontent.com/assets/4367036/19850077/d1ad4990-9f56-11e6-83ff-0c5de3587deb.png">

**Comment by marcopovitch** [comment]
![france-delay](https://cloud.githubusercontent.com/assets/4367036/22286118/6a4fa65e-e2ee-11e6-93ae-ae1b4f68a7a2.png)

**Comment by marcopovitch** [comment]
![delay-latency-geomap](https://user-images.githubusercontent.com/4367036/157223621-29a7d92b-4c7d-40be-8fce-c8a2794e1b8a.png)

**Comment by marcopovitch** [comment]
![grafana-delay-latency-board](https://user-images.githubusercontent.com/4367036/157223937-fce074a2-2500-4f63-b5e7-7adb0342d12e.jpg)

**Comment by marcopovitch** [comment]
<img width="1745" alt="sismos" src="https://user-images.githubusercontent.com/4367036/157225061-275e1f09-5ed6-48bb-95d8-7e7b1ce2f0db.png">

**Comment by yanglailai** [comment]
I am a beginner, I like what you did very much, I want to realize the function of the above picture under my Ubuntu, I want more detailed installation and operation steps, including various packages, thank you very much, please help me .

**Comment by yanglailai** [comment]
I will always pay attention to your reply, thank you
