### ISSUE TITLE
"docker-compose up -d sl2generic" do not start "grafana"

### ISSUE THREAD

**Issue by vlauciani** [marcopovitch/sl2influxdb#6]
Hi

I'm testing this project (compliments!) and running the command shown in the guide (https://github.com/marcopovitch/sl2influxdb#for-generic-seedlink-server):
```
$ docker-compose up -d sl2generic
```

only `sl2influxdb_sl2generic_1` and `sl2influxdb_influxdb_1` are run and the link `http://localhost:3000` doesn't work.

Using the command: 
```
$ docker-compose up -d grafana
```

the three dockers `sl2influxdb_grafana_1`, `sl2influxdb_sl2generic_1` and `sl2influxdb_influxdb_1` are correctly run.

Is it a guide mistake?

**Comment by marcopovitch** [comment]
Hi,  you are right !
Some instructions are missing. The README.md was just updated.
