### ISSUE TITLE
Latency Map: "n/a" message

### ISSUE THREAD

**Issue by vlauciani** [marcopovitch/sl2influxdb#8]
Hi

looking **Latency Map**, selecting a single station, I notice a `n/a` message; view image.

What does it mean?

Thank you for your support.

![screenshot 2019-02-28 at 14 49 23](https://user-images.githubusercontent.com/16477095/53571129-6ba31c00-3b68-11e9-8e61-edca6b12f245.png)

**Comment by marcopovitch** [comment]
It is bug. Should be the channel (FR.CHMF.00.HHZ: 2s for example). 
Will be fixed soon :)

**Comment by marcopovitch** [comment]
the fix has been pushed. Try it and tell me if it works for you.

**Comment by vlauciani** [comment]
ok, it works pretty well.

Thank you,
Valentino
